### ISSUE TITLE
Servo's not responding.

### ISSUE THREAD

**Issue by Afrequency** [htgdokania/FaceTrack_PiCam#1]
Hello, 

I have followed the complette instructions to create this pan tilt tracking camera. The camera and the box tracking my face work perfect, but the servos do not respond in any way. I been looking back an forth trying to find what's wrong. They work fine when used for other projeccts, but not in this one.  Do you know what could be wrong? could be something in the code, .

**Comment by htgdokania** [comment]
Please check the Pins to which you have connected the servos. In my code, I used **GPIO26 (Pin 37 )** and **GPIO19 (pin 35)** to connect the two servos ......and also make sure the Raspberry pi is getting **enough current** to move the servos.
You can also use a **separate power supply** for the servos (Maybe a power bank's  5v output) just make sure to have common ground with the pi.

If this still does not work try to run a python script just to move two servos simultaneously. If it works fine then I guess you can proceed further.

Let me know if you still face any issues. It would be my pleasure to discuss further.

**Comment by Afrequency** [comment]
It was apparently an issue with the servomove.py file(. I removed it all, extracted the zip again. And now they respond and i have a clear image from the PiCamera. And i'm fairly new to all this so, finding a problem can take a long time. I was however already using external powersources for the servos and the PiScreen. 

I maybe have another question. i've been trying to calibrate servo's for a few hours now by changing certain values, but i just can't seem to get it working like i want it  to. 

The 1st time i started it, the pan/tilt system went violently to the right, tilting up & down very fast and kept shaking. By changing some values i got it to act a little les eratic, but still very shaky, i still haven't succeded in getting the servos to their centre starting positions and when the camera detects my face, it moves way to fast andvery shaky.

I know that there are things i'm not doing correctly, but i also noticed that i'm on the right path, by the way the systems behaves when i run the code after changing.

But i could use some help. It would be nice to see it working as it should, I know by making mistakes  i learn, and i'm learning a lot :), but i'm a bit stuck. And doing everything while watching on the little PiTouchsreen makes it a little frustrating :) 

Anyway, if you have the time, that would be nice, but it's no obligation.

Greetings

**Comment by Afrequency** [comment]
Oh and, does the fact that i use digital servo's matter?

**Comment by htgdokania** [comment]
I worked on analog servos and my code was based on that only i.e. Using PWM
signals.

So basically a 1000us pulse will set the servo to 0 degreee position and
2000us pulse should set it to 180 degree position.

I don't really have much idea regarding digital servos, so that can be an
issue but as i said i have no idea in that regard.

**Comment by htgdokania** [comment]
Also i would suggest you to use remote desktop(using xrdp) to make things
simpler if you are having difficulty with the pi touch screen.
It is really convenient to use your laptop's screen,keyboard and mouse to
modify  and play with your code easily.

**Comment by Afrequency** [comment]
Ahaa :) knowing this, i can take it in a different direction. I suddenly realized that mine are digital and these send 5 to 10 times more pulses than analog servos. I will need to keep that in mind and work from there. When i figure it out i will let you know :) Could be useful :)

Oh and thank you for you project, it's actually very educational for me

**Comment by htgdokania** [comment]
Great. All the best 👍
